//! Gitea API client. API-token auth (`Authorization: token <token>`).
//!
//! The wire surface is the progenitor-generated `generated::Client`, emitted at
//! build time from `specs/gitea.openapi.json` (Gitea's Swagger 2.0 converted to
//! OpenAPI 3.0). The `gitea.*` tool surface in [`surface`] wraps each generated
//! method as an `#[orca_tool]`; endpoint CRUD + client resolution live in
//! [`tools`]; dual-substrate deploy in [`deploy`]; backup/restore in [`backup`];
//! Actions runner management in [`runner`]; CI and PR state in [`ci`].

pub mod backup;
pub mod ci;
pub mod deploy;
pub mod runner;
pub mod tools;

/// Typed Gitea client generated by `progenitor` from `specs/gitea.openapi.json`
/// at build time. Refresh the spec per the note in `build.rs`.
#[allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case
)]
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/gitea_codegen.rs"));
}

/// Auto-generated orca tool surface — `#[orca_tool]` wrappers emitted by the
/// toolkit surface pass from the codegen'd client. Each wrapper registers a
/// `gitea.<verb>` tool that resolves an endpoint via
/// [`tools::make_client`] and calls a generated method.
#[allow(non_camel_case_types, non_snake_case, clippy::all)]
pub mod surface {
    include!(concat!(env!("OUT_DIR"), "/gitea_surface.rs"));
}

/// No-op the `[[bin]]` entrypoint calls so rustc links this lib crate — and with
/// it, every `#[orca_tool]` inventory item in [`surface`], [`tools`], [`deploy`],
/// [`backup`], [`runner`] and [`ci`]. Without a reference from the bin, the whole rlib
/// (and its tool surface) is dropped at link time. See `src/main.rs`.
pub fn link_anchor() {}

use plugin_toolkit::reqwest;
use thiserror::Error;

#[derive(Debug, Clone)]
pub struct Config {
    /// API root, e.g. `https://gitea.example/api/v1`.
    pub base_url: String,
    /// Gitea personal/access token — sent as `Authorization: token <token>`.
    pub token: String,
    /// Skip TLS verification (homelab self-signed certs).
    pub insecure: bool,
}

impl Config {
    pub fn new(base_url: impl Into<String>, token: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            token: token.into(),
            insecure: false,
        }
    }

    pub fn insecure(mut self, on: bool) -> Self {
        self.insecure = on;
        self
    }

    fn auth_header_value(&self) -> String {
        format!("token {}", self.token)
    }

    /// Build the underlying `reqwest::Client` with the Gitea token header
    /// pre-attached and TLS verification toggled per `insecure`. The generated
    /// client gets this as its inner transport, so every generated method call
    /// carries auth without per-call wiring.
    pub fn build_reqwest_client(&self) -> Result<reqwest::Client, GiteaError> {
        plugin_toolkit::api_client::ApiClientBuilder::new()
            .header("authorization", self.auth_header_value())
            .and_then(|b| b.insecure(self.insecure).build())
            .map_err(|e| GiteaError::Malformed(format!("reqwest build: {e}")))
    }

    /// Build a generated `gitea::generated::Client` ready to call every codegen'd
    /// method. Base URL is the API root (e.g. `https://host/api/v1`).
    pub fn build_generated_client(&self) -> Result<generated::Client, GiteaError> {
        let http = self.build_reqwest_client()?;
        Ok(generated::Client::new_with_client(&self.base_url, http))
    }
}

#[derive(Debug, Error)]
pub enum GiteaError {
    #[error("missing required field: {0}")]
    Missing(&'static str),
    #[error("malformed gitea response: {0}")]
    Malformed(String),
    #[error("gitea transport: {0}")]
    Transport(String),
    #[error("unsupported substrate '{0}' (expected lxc | docker)")]
    BadSubstrate(String),
    #[error("deploy failed: {0}")]
    Deploy(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auth_header_is_token_scheme() {
        let cfg = Config::new("https://gitea.test/api/v1", "abc123");
        assert_eq!(cfg.auth_header_value(), "token abc123");
    }

    #[test]
    fn reqwest_client_attaches_gitea_auth_header() {
        // The cap-backed client seeds default headers onto every request, so one
        // call proves the token header is attached. We capture the `http.request`
        // JSON the shim routes through the sink and assert the header is present.
        let captured = std::sync::Arc::new(std::sync::Mutex::new(Vec::<String>::new()));
        let cap = captured.clone();
        let reply = serde_json::json!({
            "status": 200,
            "headers": [],
            "body": Vec::<u8>::from(b"ok".as_slice()),
        })
        .to_string();

        plugin_toolkit::capsink::with_cap_sink(
            Box::new(move |c: &str, json: &str| {
                assert_eq!(c, "http.request");
                cap.lock().unwrap().push(json.to_string());
                Ok(reply.clone())
            }),
            || {
                let rt = tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap();
                rt.block_on(async {
                    let cfg = Config::new("https://gitea.test/api/v1", "sekret-token");
                    let http = cfg.build_reqwest_client().unwrap();
                    let r = http.get("https://gitea.test/probe").send().await.unwrap();
                    assert_eq!(r.status().as_u16(), 200);
                });
            },
        );

        let requests = captured.lock().unwrap();
        assert_eq!(requests.len(), 1);
        assert!(
            requests[0].contains("token sekret-token"),
            "captured request missing gitea auth header: {}",
            requests[0]
        );
    }
}
